import pandas as pd
import numpy as np

from monty.serialization import loadfn, dumpfn

from pymatgen.ext.matproj import MPRester

from pymatgen import Composition
import json
from pymatgen import Structure, Lattice
from pumml.learners import PULearner
from matminer.featurizers.structure import DensityFeatures, GlobalSymmetryFeatures
from matminer.featurizers.composition import Meredig, CohesiveEnergy


class PUPredict:
    def _init_(self):
        """An extension of class PULearner which uses a machine learning
       model to predict synthesizability of all compounds in Materials Project
       Database


        Features for training data are generated by first-principles 
        (density functional theory) calculations, or structural or chemical
        data looked up from Materials Project Database


        Two models each for F-Block data and D-Block data have been pre-trained
        which are used to predict synthesizability of compounds based on the block
        they belong to. 


        Attributes:
            func_input (str, pymatgen.core.structure.Structure): Input to the fucntion

            api_key (str): valid api_key to access materials project database 
            mp_ids(list): Contains the materials project IDs of input samples
            df_input(DataFrame): Pandas DataFrame whcih conatains features from Materials Project Database of the input samples
            df_extracted(DataFrame): Pandas DataFrame which contains features of input samples extracted using Matminer 
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


        """
        self.func_input = None
        self.api_key = None

    def mpr(self):
        """
        Setting the input API-Key into a function 
        Args:
            None
        Returns:
            MPRester(function): A function which is used to extract data from Materials Project 
      """
        return MPRester(api_key=self.api_key)

    def get_mp_id(self, updated_input):
        """

       Gets the Materials IDs from the database

        Args:
            updated_input (criteria): The condition on which the data is extracted

        Returns:
            mp_ids (list): List of MP-IDs


      """

        criteria = updated_input

        # get mp-id
        mpids = []
        with self.mpr() as m:
            mp_ids = m.query(criteria, ["material_id"], chunk_size=0)

        mp_ids = [mpid["material_id"] for mpid in mp_ids]

        return mp_ids

    def get_formula(self, updated_input):
        """

       Gets the full formula from Materials Project

        Args:
            updated_input (criteria): The condition on which the data is extracted

        Returns:
            formula (str): A string which contains the formula of the input


      """
        criteria = updated_input

        formula = []

        # get formualae
        with self.mpr() as m:
            formula = m.query(criteria, ["full_formula"], chunk_size=0)

        formula = [id["full_formula"] for id in formula]

        return formula[0]

    def get_data(self, mp_ids):
        """

       Gets features of the Materials IDs from the database

        Args:
            mp_ids (list): List of MP-IDs

        Returns:
            df_input(DataFrame): Pandas DataFrame whcih conatains features from Materials Project Database of the input samples


      """
        chunk_size = 1000
        sublists = [
            mp_ids[i : i + chunk_size] for i in range(0, len(mp_ids), chunk_size)
        ]
        # MPRester.supported_properties
        properties = [
            "theoretical",
            "energy_per_atom",
            "formation_energy_per_atom",
            "e_above_hull",
            "icsd_ids",
            "material_id",
            "structure",
        ]

        data = []
        # Get all materials from MP by mpid
        with self.mpr() as m:
            for sublist in sublists:
                data += m.query(
                    {"material_id": {"$in": sublist}}, properties=properties
                )

        df_input = pd.DataFrame(data)

        # PU_label is 1 (0) if experimental crystal structure exists (doesn't exist)
        df_input["PU_label"] = df_input.theoretical.apply(
            lambda x: 0 if x == True else 1
        )

        # Converting 'material_id' to list datatype
        mp_id = df_input["material_id"].tolist()

        return df_input

    def check_for_block(comp):
        """

       Check whehther it belongs to D-Block or F-Block. If the compound contains even one element from F-block, then the compound is 
       termed ad F-block compound, else it is termed as Non-F Block compound

        Args:
            comp (pymatgen.core.composition.Composition): Contains the composition of the the input sample

        Returns:
            k (boolean value): 0 if it belongs to F-block, 1 if it belongs to non-fblock


      """
        # check which block it belongs to
        if comp.contains_element_type("f-block") == True:
            return 0  # Belongs to F-block
        else:
            return 1  # Belongs to Non F-block

    def check_for_theortical(self, updated_input):
        """

       Check if the input is theortical or experimental and drop the experimental compounds

        Args:
            updated_input (criteria): The condition on which the data is extracted

        Returns:
            mp_ids (list): List of MP-IDs
            df_input(DataFrame): Pandas DataFrame whcih conatains features from Materials Project Database of the input samples


      """
        # Get Mp-IDs
        mp_id = self.get_mp_id(updated_input)

        # Get Features of input
        df_input = self.get_data(mp_id)

        # Print the MP-ID for experimental compounds
        for i in range(len(mp_id)):
            if df_input.theoretical.values[i] == False:
                print(
                    "The given input with material_id ",
                    df_input.material_id.values[i],
                    " exists.",
                )

        # Update the df_input by removing experimental compounds
        j = df_input[(df_input.theoretical == False)].index
        df_input = df_input.drop(j)

        return mp_id, df_input

    def check_if_already_exists(self, comp, updated_input):
        """

       Check if the input exists in pre-trained model

        Args:
            updated_input (criteria): The condition on which the data is extracted
            comp (pymatgen.core.composition.Composition): Contains the composition of the the input sample


        Returns:
            mp_ids (list): List of MP-IDs
            df_input(DataFrame): Pandas DataFrame whcih conatains features from Materials Project Database of the input samples
            k (boolean value): 0 if it belongs to F-block, 1 if it belongs to Non F block 
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


      """
        mp_id, df_input = self.check_for_theortical(updated_input)
        k = PUPredict.check_for_block(comp)

        # Intialise Synthesizability Score
        synth_score = []

        # Load F-Block pre-trained Model
        if k == 0:
            fblock_trained = pd.read_json(
                "/content/gdrive/My Drive/Upenn/fblock_trained_model.json"
            )
            mp_id_theo = df_input.material_id.values
            for i in mp_id_theo:
                if i in fblock_trained.material_id.values:
                    synth_score.append(
                        fblock_trained.synth_score[
                            fblock_trained.material_id == i
                        ].values
                    )
                    j = df_input[(df_input.material_id == i)].index
                    df_input = df_input.drop(j)

        # Load D-Block pre-trained Model
        elif k == 1:
            dblock_trained = pd.read_json(
                "/content/gdrive/My Drive/Upenn/dblock_trained_model.json"
            )
            mp_id_theo = df_input.material_id.values
            for i in mp_id_theo:
                if i in dblock_trained.material_id.values:
                    synth_score.append(
                        dblock_trained.synth_score[
                            dblock_trained.material_id == i
                        ].values
                    )
                    j = df_input[(df_input.material_id == i)].index
                    df_input = df_input.drop(j)

        return k, mp_id, synth_score, df_input

    def extract_features(df_input):
        """

       Extract features using Matminer from the 'structure' column in df_input

        Args:
            df_input(DataFrame): Pandas DataFrame whcih conatains features from Materials Project Database of the input samples


        Returns:
            df_extracted(DataFrame): Pandas DataFrame which contains features of input samples extracted using Matminer


      """
        # Dropping the 'theoretical' column
        df_input.drop(columns=["theoretical"], inplace=True)

        dfeat = DensityFeatures()
        symmfeat = GlobalSymmetryFeatures()
        mfeat = Meredig()
        cefeat = CohesiveEnergy()

        featurizers = {"density": dfeat, "symmetry": symmfeat, "Meredig": mfeat}

        # Initalising empty lists
        densities, vpas, pfs, sgns, cenergies, maw, rar, mar, ren, men, mpids = (
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        )
        for row in df_input.itertuples():
            s = row[6]
            f1, f2, f3, f4, f5, f6, f7, f8, f9, f10 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            try:
                mpid = row[5]
                mpids.append(mpid)
                fepa = row[2]
                c = s.composition

                f = dfeat.featurize(s)
                f1 = f[0]
                f2 = f[1]
                f3 = f[2]

                f = symmfeat.featurize(s)
                f4 = f[0]

                f = cefeat.featurize(c, formation_energy_per_atom=fepa)
                f5 = f[0]

                f = mfeat.featurize(c)
                f6 = f[-17]
                f7 = f[-12]
                f8 = f[-11]
                f9 = f[-10]
                f10 = f[-9]

            except:
                pass

            densities.append(f1)
            vpas.append(f2)
            pfs.append(f3)
            sgns.append(f4)
            cenergies.append(f5)
            maw.append(f6)
            rar.append(f7)
            mar.append(f8)
            ren.append(f9)
            men.append(f10)

        # Create DataFrame from the extratced features
        df_feats = pd.DataFrame(
            {
                "material_id": mpids,
                "density": densities,
                "vpa": vpas,
                "packing fraction": pfs,
                "spacegroup_num": sgns,
                "cohesive_energy": cenergies,
                "mean AtomicWeight": maw,
                "range AtomicRadius": rar,
                "mean AtomicRadius": mar,
                "range Electronegativity": ren,
                "mean Electronegativity": men,
            }
        )

        # Merging it with df_input on basis of 'material-id'
        df_featurized = df_input.merge(df_feats, on="material_id")

        # Drop 'structure' column
        df_featurized.drop(columns=["structure"], inplace=True)

        # ignore compounds that failed to featurize
        df_extracted = df_featurized.fillna(df_input.mean()).query(
            "cohesive_energy > 0.0"
        )

        # Re-arranging the 'PU Label' column
        pu_label = df_extracted["PU_label"]
        df_extracted = df_extracted.drop(["PU_label"], axis=1)
        df_extracted["PU_label"] = pu_label

        # Drop the icsd_ids column
        df_extracted.drop(columns=["icsd_ids"], inplace=True)

        return df_extracted

    def append_data(df_extracted, k):
        """

       Extract features using Matminer from the 'structure' column in df_input

        Args:
            df_extracted(DataFrame): Pandas DataFrame which contains features of input samples extracted using Matminer
            k (boolean value): 0 if it belongs to F-block, 1 if it belongs to Non F block


        Returns:
            df(DataFrame): Pandas DataFrame which contains features of input samples extracted using Matmimer along with training data
            input_ids(numpy array): MP-IDs of updated input compounds


      """
        # append data to the respective block
        input_ids = df_extracted.material_id.values

        # If it belongs to 'F-block'
        if k == 0:
            # F-Block training Dataset
            fblock_features = pd.read_json(
                "/content/gdrive/My Drive/Upenn/fblock_extracted_features.json"
            )
            df = fblock_features.append(df_extracted)
            df.reset_index(drop=True, inplace=True)

        # If it belongs to 'D-Block'
        else:
            # D-Block training dataset
            dblock_features = pd.read_json(
                "/content/gdrive/My Drive/Upenn/dblock_featurized_30k.json"
            )
            df = dblock_features.append(df_extracted)
            df.reset_index(drop=True, inplace=True)

        return input_ids, df

    def do_pulearner(input_ids, df):
        """

       Train the model using PULearner

        Args:
            df(DataFrame): Pandas DataFrame which contains features of input samples extracted using Matmimer along with training data
            input_ids(numpy array): MP-IDs of updated input compounds


        Returns:
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


      """

        # Run PUMML
        df.to_json("test.json")
        pul = PULearner()

        # Set hyperparameters
        n_splits = 10  # kfold CV
        n_repeats = 3  # Repeat the entire kfold CV n times for averaging
        n_bags = 100  # bags for bootstrap aggregating.

        pu_stats = pul.cv_baggingDT(
            "test.json", splits=n_splits, repeats=n_repeats, bags=n_bags
        )
        df1 = pul.df_U.copy()
        df1["synth_score"] = pu_stats["prob"]

        # Initialsing synth_score
        synth_score = []
        for i in range(len(input_ids)):
            synth_score.append(df1.synth_score[df1.material_id == input_ids[i]].values)

        return synth_score

    def material_id(self, func_input, api_key):

        """

       Takes input in form of material ID from materials project and returns the synthesizability score for the same.

        Args:
            func_input (str): Input to the fucntion should be in string format. For eg: 'mp-1234'
            api_key (str): valid api_key to access materials project database. Should be in string format. To get your api_key, head to https://materialsproject.org/open


        Returns:
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


      """
        # Updating the criteria
        updated_input = {"material_id": func_input}

        # Setting API_key for materials project
        self.api_key = api_key

        # Extracting formula
        formula = self.get_formula(updated_input)

        # Extracting composition
        comp = Composition(formula)

        # Extracting MP-IDs
        mp_id = self.get_mp_id(updated_input)

        # If Input given is invalid
        if len(mp_id) == 0:
            return "No such compound exists in Materials Project Database"

        # Checking if it already exists in pre-trained model
        k, mp_id, synth_score, df_input = self.check_if_already_exists(
            comp, updated_input
        )

        # If found in pre-trained models, report synth_scores
        if df_input.shape[0] == 0:
            if len(synth_score) != 0:
                return synth_score

        # Else, train the model and report scores
        else:
            df_extracted = self.extract_features(df_input)
            input_ids, df = self.append_data(df_extracted, k)
            score = self.do_pulearner(input_ids, df)
            synth_score.append(score)
            print(synth_score)
            return synth_score

    def full_formula(self, func_input, api_key):
        """

       Takes input in form of full formula and returns the synthesizability score for the same.

        Args:
            func_input (str): Input to the fucntion should be in string format. For eg: 'Ba2Yb2Al4Si2N10O4'
            api_key (str): valid api_key to access materials project database. Should be in string format. To get your api_key, head to https://materialsproject.org/open


        Returns:
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


      """
        # Updating the criteria
        updated_input = {"full_formula": func_input}

        # Setting API Key
        self.api_key = api_key

        # Extracting the composition
        comp = Composition(func_input)

        # Extracting the MP-IDs
        mp_id = self.get_mp_id(updated_input)

        # If Input given is invalid
        if len(mp_id) == 0:
            return "No such compound exists in Materials Project Database"

        # Checking if it already exists in pre-trained model
        k, mp_id, synth_score, df_input = self.check_if_already_exists(
            comp, updated_input
        )

        # If found in pre-trained models, report synth_scores
        if df_input.shape[0] == 0:
            if len(synth_score) != 0:
                return synth_score

        # Else, train the model and report scores
        else:
            df_extracted = self.extract_features(df_input)
            input_ids, df = self.append_data(df_extracted, k)
            score = self.do_pulearner(input_ids, df)
            synth_score.append(score)
            print(synth_score)
            return synth_score

    def pymatgen_structure(self, func_input, api_key):
        """

       Takes input in form of Pymatgen Structure Object and returns the synthesizability score for the same.

        Args:
            func_input (pymatgen.core.structure.Structure): Input to the fucntion should be in pymatgen.core.structure.Structure format. For more information, refer to test files
            api_key (str): valid api_key to access materials project database. Should be in string format. To get your api_key, head to https://materialsproject.org/open


        Returns:
            synth_scores (list): Synthesizability scores (between 0 and 1) of
                given sample.


      """
        # Setting API Key
        self.api_key = api_key

        # Extract formula and remove the spaces between them
        formula = func_input.formula
        formula = formula.replace(" ", "")

        # Extract the composition
        comp = Composition(formula)

        # Update the criteria
        updated_input = {"full_formula": formula}

        # Extract MP-IDs
        mp_id = self.get_mp_id(updated_input)

        # If Input given is invalid
        if len(mp_id) == 0:
            return "No such compound exists in Materials Project Database"

        # Checking if it already exists in pre-trained model
        k, mp_id, synth_score, df_input = self.check_if_already_exists(
            comp, updated_input
        )

        # If found in pre-trained models, report synth_scores
        if df_input.shape[0] == 0:
            if len(synth_score) != 0:
                return synth_score

        # Else, train the model and report scores
        else:
            df_extracted = self.extract_features(df_input)
            input_ids, df = self.append_data(df_extracted, k)
            score = self.do_pulearner(input_ids, df)
            synth_score.append(score)
            print(synth_score)
            return synth_score
